Add Provider edit endpoint!
InternetSemLimites/PublicAPI pull request #35
Opened 2017-01-14 22:56 UTC by jonatasbaldin

Esse PR adicionar o endpoint `/api/provider/:id/edit/` na API, possibilitando que usuários possam editar provedores que já existam.

Mesmo que não seja muito RESTful, criei o endpoint usando `POST`, pois fica mais simples de acordo com o código já existente.

Outra liberdade que tomei foi a de setar o `status` da instância para `NEW` quando editada. Acho que seja suficiente para que a edição passe pela moderação, mas se acharem melhor, podemos adicionar um novo status `EDITED`.

Pra finalizar, é meu primeiro PR nesse projeto 💃  valeu @cuducos pelo toque!

2017-01-15 14:51 UTC, cuducos requested changes
Oi @jonatasbaldin! Muito obrigado pelo PR.

Comentei alguns detalhes no código, mas o principal que me pergunto agora é: _seria essa a melhor estratégia_?

Pergunto isso pois uma vez enviado a _sugestão_ de edição a gente perde os dados anteriores do provedor.

Acho que o ideal seria algo que funcionasse mais ou menos assim:

* Ao enviar uma sugestão de edição, o provedor original não é alterado e continua publicado
* A moderação recebe um email com os dados originais e as alterações sugeridas
* Se a alteração for recusada, a sugestão de alteração é arquivada e o antigo registro continua inalterado e publicado
* Se a alteração for aceita, pode rolar uma espécie de _merge_ (não sei se deletamos um ou outro registro, mas não precisamos dos dois; por mim deixa tudo no banco, dá para trabalhar isso com os status… mas não precisa)

Talvez precisamos pensar mais nos status, adicionar algo como:

* `EDIT`: Edição aguardando moderação
* `OUTDATED`: Substituído por versão atualizada

Por fim, podemos fazer também um endpoint para um formulário de edição em `/edit/<pk>/`.

O que acha?

Se quiser parear, me avisa e tocamos algumas coisas juntos. E se deu pra bola desse projeto, só avisa que assumo daqui pra frente!

2017-01-15 14:51 UTC, cuducos commented on InternetSemLimites/api/urls.py
> +    url(r'^provider/(?P<pk>[\d]+)/edit/$', provider_edit, name='edit'),
Eu votaria por uma API mais RESTful: `GET /provider/<id>/` para ler, `PUT /provider/<id>/` para editar. O `urls.py` ficaria intacto, e no `views.py` poderíamos ter algo como:

```python
def provider(request, pk):
    routes = {
        'GET': provider_view,
        'PUT': provider_edit
    }
    route = routes.get(request.method)
    if route:
        return route(request, pk)
    return HttpResponseNotAllowed(['GET', 'PUT'])


def provider_view(request, pk):
    # old provider view


def provider_edit(request, pk):
    # provider_edit view from the PR
```

Ou a gente pode usar as views do Django REST Frameworks também ; )

2017-01-15 14:51 UTC, cuducos commented on InternetSemLimites/api/views.py
> +    provider = Provider.objects.get(pk=pk)
Que tal [`get_object_or_404(Provider, pk=pk)`](https://docs.djangoproject.com/en/1.10/topics/http/shortcuts/#get-object-or-404)?

2017-01-15 14:51 UTC, cuducos commented on InternetSemLimites/api/views.py
> +        return JsonResponse({'errors': provider_form.errors})
Aqui a gente não deveria retornar status HTTP 200, deveria ser 422, não? Que tal `JsonResponse({'errors': provider_form.errors}, status=422)`?

2017-01-15 14:51 UTC, cuducos commented on InternetSemLimites/core/models.py
> +    def coverage_id_to_list(self):
Se a gente só vai usar isso nos testes, acho que não precisamos dela no modelo…

2017-01-17 01:58 UTC, jonatasbaldin commented on InternetSemLimites/api/urls.py
> +    url(r'^provider/(?P<pk>[\d]+)/edit/$', provider_edit, name='edit'),
Sobre essa questão, Django não suporta `PUT` por padrão, somente `POST`.

Poderíamos usar o `POST` mesmo ou usar o Django REST Framework. Porém, acho o último meio overkill se for usar em somente uma view.

Fiz com o `POST` e funcionou bem, mas não ficar tão RESTful 😞

2017-01-17 01:58 UTC, jonatasbaldin commented on InternetSemLimites/api/views.py
> +    provider = Provider.objects.get(pk=pk)
Show, usando!

2017-01-17 01:59 UTC, jonatasbaldin commented on InternetSemLimites/api/views.py
> +        return JsonResponse({'errors': provider_form.errors})
Adicionado!

2017-01-17 01:59 UTC, jonatasbaldin commented on InternetSemLimites/core/models.py
> +    def coverage_id_to_list(self):
Coloquei no teste.

2017-01-17 02:00 UTC, jonatasbaldin commented on InternetSemLimites/api/urls.py
> +    url(r'^provider/(?P<pk>[\d]+)/edit/$', provider_edit, name='edit'),
Logo subo o código usando o `POST`. Caso não fique legal, vou planejar pra implementer o `DRF`.

2017-01-17 02:44 UTC, jonatasbaldin commented
Novas mudanças!

Bem, acatei totalmente a estratégia de duplicar os provedores, arquivar etc.
Para isso, adicionei os status:
* `EDIT`: Quando o provider está em estado de edição.
* `OUTDATED`: Quando o provider editado foi aceito e o antigo ficar desatualizado.
* `ARCHIVED`: Quando o provider feito para edição foi negado.

Também adicionei um novo campo `edited_from`. Com ele consigo referenciar qual provedor está sendo editado.

Sobre o RESTful, como disse logo acima, só há `POST` no Django, por isso implementei esse método HTTP. Na minha opinião, caso for usar o DRF, vale um refactor pra utilizar as ViewSets, Serializers etc. Se for o intuito de fazer isso na plataforma agora, #VamoDale.

Outras coisinhas:
* Adicionei um método no Djando Admin para invalidar o provedor original, caso sua edição seja aceita.
* Adicionei um novo template de email para edição.
* Refatorei os testes.

Acho que é isso, qualquer coisa dá um toque 💃

2017-01-17 02:46 UTC, jonatasbaldin commented
O `coveralls` deu uma queda ali, não manjo como testar o código do Django Admin.

Vou ver se acho amanhã, se souber dá um grito aí tb.

2017-01-17 09:48 UTC, cuducos reviewed
Tá demais agora, sensacional!

Adicionei pequenas sugestões, mas LGTM to me ; )

Me diga se vais tentar fazer os testes (e ver minhas sugestões), aí espero para dar _merge_ se for o caso… senão já dou _merge_ e abro issue o teste.

2017-01-17 09:48 UTC, cuducos commented on InternetSemLimites/api/views.py
> +    return HttpResponseNotAllowed(['GET', 'POST'])
Totalmente frescura agora, mas para evitar repetição (leia-se: bugs na manutenção futura) pensei, relendo esse código, que poderia ser `return HttpResponseNotAllowed(routes.keys())` (talvez tenha que transformar em lista). A ideia é só fazer o controle dos métodos em um lugar, não em dois ; )

2017-01-17 09:48 UTC, cuducos commented on InternetSemLimites/api/views.py
> +
Acho que a gente pode tentar não fazer duas _queries_ no banco. O campo `edited_from` (`ForeignKey`) deve aceitar só uma `pk`. Então esse bloco todo poderia ser algo como (mas só rascunhando aqui, não testei):

```python
provider = get_object_or_404(Provider, pk=pk)
provider.edited_from = int(provider.pk)  # forcing int here just as a way to copy the data vs. instantiate it
provider.pk = None
provider.status = Provider.EDIT
```

2017-01-17 09:48 UTC, cuducos commented on InternetSemLimites/api/views.py
> +    fields.remove('edited_from')
Talvez melhorar esse monte de `.remove`:

```
all_fields = set(f.__str__().split('.')[-1] for f in Provider._meta.fields)
ignore_fields = set('id', 'status', 'edited_from')
fields = tuple(all_fields - ignore_fields)
```

2017-01-17 09:48 UTC, cuducos commented on InternetSemLimites/core/models.py
> +              (ARCHIVED, 'Arquivado'))
_Arquivado_ seria sugestão de edição recusada, é isso? Se for, acho que podemos usar o `REFUSED` mesmo…

2017-01-17 22:25 UTC, jonatasbaldin commented on InternetSemLimites/api/views.py
> +    return HttpResponseNotAllowed(['GET', 'POST'])
Tu é muito Pythonico meu brother hahah Dá pra fazer com `HttpResponseNotAllowed([method for method in routes])`.

2017-01-17 22:39 UTC, cuducos commented on InternetSemLimites/api/views.py
> +    return HttpResponseNotAllowed(['GET', 'POST'])
Para comentários como esse que fiz costumo usar esse emoji: 💅 hahaha…

2017-01-17 22:52 UTC, jonatasbaldin commented on InternetSemLimites/api/views.py
> +
O problema é que eu preciso copiar todas as informações do `provider_original` para o `provider_edited` e ter os dois objetos na lógica, para poder mandar o email com as informações depois. No caso que você rascunhou, é editado o próprio objeto que já está no banco, e não feito uma cópia (assim não conseguimos arquivar o antigo etc).

A questão é que se eu não fizer duas consultas no banco, o objeto se torna o mesmo. Exemplo:
```
>>> provider_original = get_object_or_404(Provider, pk=1)
>>> id(provider_original)
4475570664
>>> provider_edited = provider_original
>>> id(provider_edited)
4475570664
```

Mas se eu fizer duas consultas, eu tenho dois objetos diferentes, no qual posso manipulá-los sem problema:
```
>>> provider_original = get_object_or_404(Provider, pk=1)
>>> id(provider_original)
4475569992
>>> provider_edited = get_object_or_404(Provider, pk=1)
>>> id(provider_edited)
4475570888
```

Mas acho que achei outra solução, usando `deepcopy` do Python, ele gera outro ID!
```
>>> from copy import deepcopy
>>> provider_original = get_object_or_404(Provider, pk=1)
>>> provider_edited = deepcopy(provider_original)
>>> id(provider_original)
4475571392
>>> id(provider_edited)
4475143896
```

2017-01-17 23:03 UTC, jonatasbaldin commented on InternetSemLimites/api/views.py
> +    fields.remove('edited_from')
:top: 

Só a segunda linha precisa ser `ignore_fields = set(['id', 'status', 'edited_from'])`. Por padrão, o `set` só aceita um argumento, mas passando uma lista funciona!

2017-01-17 23:07 UTC, jonatasbaldin commented on InternetSemLimites/core/models.py
> +              (ARCHIVED, 'Arquivado'))
Beleza! Vou remover a migration e resetar o `model.py`.

2017-01-17 23:13 UTC, jonatasbaldin commented on InternetSemLimites/core/models.py
> +              (ARCHIVED, 'Arquivado'))
Beleza, só removi as alterações do `models.py` e do arquivo de migração.

2017-01-17 23:13 UTC, jonatasbaldin commented on InternetSemLimites/api/views.py
> +    return HttpResponseNotAllowed(['GET', 'POST'])
O meu é o 💃

2017-01-17 23:43 UTC, jonatasbaldin commented
Rolou os testes, coverage chiou do `HttpResponseNotAllowed([method for method in routes])` ainda, mas tá em 100% hahaha

Quer rolar mais testes ainda, ou bora dar um merge? 🚀

2017-01-18 11:05 UTC, merged